# Generated by Django 3.0 on 2019-01-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190128_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='club',
            name='count',
            field=models.IntegerField(),
        ),
    ]
