# Generated by Django 3.0 on 2019-02-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190128_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='ownername',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
