# Generated by Django 3.0 on 2019-02-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_club_ownername'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountblog',
            name='time',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubblog',
            name='time',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='information',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accountblog',
            name='message',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='information',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clubblog',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
