# Generated by Django 3.0 on 2019-02-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190212_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountblog',
            options={'ordering': ['time']},
        ),
    ]
