# Generated by Django 3.0 on 2019-02-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190219_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('signtime', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='ClubSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AlterModelOptions(
            name='accountblog',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='clubblog',
            options={'ordering': ['-time']},
        ),
    ]
