# Generated by Django 3.0 on 2019-02-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190220_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderid', models.CharField(max_length=40)),
                ('receiverid', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
